apiVersion: v1
data:
  application.yaml: |-
    server:
      port: 8080
    logging:
      level:
        org:
          springframework:
            cloud:
              kubernetes: TRACE
kind: ConfigMap
metadata:
  name: spring-cloud-kubernetes-configuration-watcher
