name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The GitHub Environment with the required Azure credentials and AKS cluster details
        type: environment
        required: true

env:
  SKAFFOLD_INTERACTIVE: false
  SKAFFOLD_UPDATE_CHECK: false
  SKAFFOLD_VERBOSITY: warning # Log level: one of [panic fatal error warning info debug trace]

jobs:
  Deploy:
    name: "Deploy spring-cloud-kubernetes-configuration-watcher"
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_REGISTRY_NAME }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2
        # with:
        #   version: '<version>' # default is latest stable

      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.0.32"

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_CLUSTER_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          admin: "false"
          use-kubelogin: "true"

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        # with:
        #   version: '<version>' # default is latest stable

      - name: Install Skaffold
        run: |
          echo "Install Skaffold:"
          mkdir -p $HOME/.local/bin/
          curl --fail --retry 3 --location https://github.com/GoogleContainerTools/skaffold/releases/download/v1.35.1/skaffold-linux-amd64 --output $HOME/.local/bin/skaffold
          chmod +x $HOME/.local/bin/skaffold
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          skaffold version
          skaffold config set --global collect-metrics false
          skaffold config set default-repo ${{ secrets.ACR_REGISTRY_NAME }}

      - name: Deploy
        run: |
          export cluster=$( kubectl config current-context )
          echo "Deploying to cluster ${cluster}"#

          skaffold run

          POD_NAME=$(kubectl get pods --namespace default -l "app=spring-cloud-kubernetes-configuration-watcher" -o jsonpath="{.items[0].metadata.name}")
          echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV
        shell: bash

      - name: kubectl logs
        run: |
          echo ""
          echo "To check logs run:"
          echo ""
          echo "kubectl logs -f $POD_NAME"
